"""apiDoc.js -> Markdown converter.

Parses the api_data.js / api_project.js files generated by apidoc
(https://apidocjs.com) and converts the structured API data into
Markdown documentation.

The api_data.js file contains a JavaScript variable assignment like:
  define({ "api": [ ... ] })
or:
  var api = [ ... ];

We extract the JSON array from it and convert each endpoint entry
into a structured Markdown section grouped by apiGroup.
"""

import json
import logging
import re

logger = logging.getLogger(__name__)

_DEFINE_PATTERN = re.compile(
    r"define\(\s*(\{.*\})\s*\)", re.DOTALL
)
_VAR_PATTERN = re.compile(
    r"(?:var|let|const)\s+api\s*=\s*(\[.*?\])\s*;", re.DOTALL
)
_PROJECT_DEFINE_PATTERN = re.compile(
    r"define\(\s*(\{.*\})\s*\)", re.DOTALL
)


def _extract_json_from_js(js_text: str) -> list | dict | None:
    """Extract JSON data from apidoc-generated JS file."""
    m = _DEFINE_PATTERN.search(js_text)
    if m:
        try:
            data = json.loads(m.group(1))
            if isinstance(data, dict) and "api" in data:
                return data["api"]
            return data
        except (json.JSONDecodeError, ValueError):
            pass

    m = _VAR_PATTERN.search(js_text)
    if m:
        try:
            return json.loads(m.group(1))
        except (json.JSONDecodeError, ValueError):
            pass

    try:
        return json.loads(js_text)
    except (json.JSONDecodeError, ValueError):
        pass

    return None


def _extract_project_from_js(js_text: str) -> dict | None:
    """Extract project metadata from api_project.js."""
    m = _PROJECT_DEFINE_PATTERN.search(js_text)
    if m:
        try:
            return json.loads(m.group(1))
        except (json.JSONDecodeError, ValueError):
            pass
    try:
        data = json.loads(js_text)
        if isinstance(data, dict):
            return data
    except (json.JSONDecodeError, ValueError):
        pass
    return None


def _render_fields(fields: list[dict], table_title: str = "") -> list[str]:
    """Render a list of apidoc field objects as a Markdown table."""
    if not fields:
        return []
    lines: list[str] = []
    if table_title:
        lines.append(f"**{table_title}:**")
        lines.append("")
    lines.append("| Field | Type | Description |")
    lines.append("|---|---|---|")
    for f in fields:
        if not isinstance(f, dict):
            continue
        name = f.get("field", "")
        ftype = f.get("type", "")
        desc = f.get("description", "").replace("\n", " ").strip()
        desc = re.sub(r"</?p>", "", desc)
        optional = f.get("optional", False)
        if optional:
            name = f"{name} *(optional)*"
        default = f.get("defaultValue")
        if default is not None:
            desc += f" (default: `{default}`)"
        lines.append(f"| `{name}` | {ftype} | {desc} |")
    lines.append("")
    return lines


def _render_endpoint(entry: dict) -> list[str]:
    """Render a single apidoc endpoint entry to Markdown lines."""
    method = entry.get("type", "GET").upper()
    url = entry.get("url", "")
    title = entry.get("title", "") or entry.get("name", "")
    description = entry.get("description", "").strip()
    description = re.sub(r"</?p>", "", description)

    lines: list[str] = []
    lines.append(f"### {method} {url}")
    lines.append("")
    if title:
        lines.append(f"**{title}**")
        lines.append("")
    if description and description != title:
        lines.append(description)
        lines.append("")

    permission = entry.get("permission")
    if permission:
        perm_names = []
        for p in permission:
            if isinstance(p, dict):
                perm_names.append(p.get("name", ""))
            elif isinstance(p, str):
                perm_names.append(p)
        if perm_names:
            lines.append(f"**Permission:** {', '.join(perm_names)}")
            lines.append("")

    header = entry.get("header", {})
    if isinstance(header, dict) and header.get("fields"):
        for group_name, fields in header["fields"].items():
            lines.extend(_render_fields(fields, f"Header — {group_name}"))

    parameter = entry.get("parameter", {})
    if isinstance(parameter, dict):
        if parameter.get("fields"):
            for group_name, fields in parameter["fields"].items():
                label = "Parameters" if group_name == "Parameter" else f"Parameters — {group_name}"
                lines.extend(_render_fields(fields, label))
        examples = parameter.get("examples", [])
        for ex in examples:
            if isinstance(ex, dict):
                ex_title = ex.get("title", "Example")
                ex_content = ex.get("content", "")
                if ex_content:
                    lines.append(f"**{ex_title}:**")
                    lines.append("")
                    lang = ex.get("type", "json")
                    lines.append(f"```{lang}")
                    lines.append(ex_content)
                    lines.append("```")
                    lines.append("")

    success = entry.get("success", {})
    if isinstance(success, dict):
        if success.get("fields"):
            for group_name, fields in success["fields"].items():
                label = "Success Response" if group_name in ("Success 200", "200") else f"Success — {group_name}"
                lines.extend(_render_fields(fields, label))
        examples = success.get("examples", [])
        for ex in examples:
            if isinstance(ex, dict):
                ex_title = ex.get("title", "Success Response Example")
                ex_content = ex.get("content", "")
                if ex_content:
                    lines.append(f"**{ex_title}:**")
                    lines.append("")
                    lang = ex.get("type", "json")
                    lines.append(f"```{lang}")
                    lines.append(ex_content)
                    lines.append("```")
                    lines.append("")

    error = entry.get("error", {})
    if isinstance(error, dict):
        if error.get("fields"):
            for group_name, fields in error["fields"].items():
                lines.extend(_render_fields(fields, f"Error — {group_name}"))
        examples = error.get("examples", [])
        for ex in examples:
            if isinstance(ex, dict):
                ex_title = ex.get("title", "Error Response Example")
                ex_content = ex.get("content", "")
                if ex_content:
                    lines.append(f"**{ex_title}:**")
                    lines.append("")
                    lang = ex.get("type", "json")
                    lines.append(f"```{lang}")
                    lines.append(ex_content)
                    lines.append("```")
                    lines.append("")

    return lines


def apidoc_to_markdown(
    api_data: list[dict],
    project: dict | None = None,
) -> str:
    """Convert parsed apidoc api_data array to Markdown.

    Args:
        api_data: List of endpoint entries from api_data.js.
        project: Optional project metadata from api_project.js.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    proj_title = ""
    proj_version = ""
    proj_description = ""

    if project:
        proj_title = project.get("title", project.get("name", ""))
        proj_version = project.get("version", "")
        proj_description = project.get("description", "")

    if proj_title:
        header = f"# {proj_title}"
        if proj_version:
            header += f" v{proj_version}"
        lines.append(header)
    else:
        lines.append("# API Documentation")
    lines.append("")

    if proj_description:
        lines.append(re.sub(r"</?p>", "", proj_description).strip())
        lines.append("")

    if project:
        url = project.get("url", "")
        if url:
            lines.append(f"**URL:** {url}")
            lines.append("")

    groups: dict[str, list[dict]] = {}
    for entry in api_data:
        if not isinstance(entry, dict):
            continue
        group = entry.get("group", "default")
        groups.setdefault(group, []).append(entry)

    group_titles: dict[str, str] = {}
    for entry in api_data:
        if isinstance(entry, dict) and entry.get("groupTitle"):
            group_titles[entry["group"]] = entry["groupTitle"]

    lines.append("---")
    lines.append("")

    for group_name, endpoints in groups.items():
        display_name = group_titles.get(group_name, group_name)
        lines.append(f"## {display_name}")
        lines.append("")

        group_desc = ""
        for ep in endpoints:
            if isinstance(ep, dict) and ep.get("groupDescription"):
                group_desc = ep["groupDescription"]
                break
        if group_desc:
            lines.append(re.sub(r"</?p>", "", group_desc).strip())
            lines.append("")

        for ep in endpoints:
            lines.extend(_render_endpoint(ep))

    return "\n".join(lines)


def parse_apidoc_js(api_data_js: str, api_project_js: str = "") -> tuple[str, dict]:
    """Parse apidoc JS files and return (markdown, metadata).

    Args:
        api_data_js: Content of api_data.js file.
        api_project_js: Content of api_project.js file (optional).

    Returns:
        Tuple of (markdown_text, metadata_dict).

    Raises:
        ValueError: If api_data.js cannot be parsed.
    """
    api_data = _extract_json_from_js(api_data_js)
    if not api_data or not isinstance(api_data, list):
        raise ValueError("Failed to parse api_data.js: no valid API entries found")

    project: dict | None = None
    if api_project_js:
        project = _extract_project_from_js(api_project_js)

    md_text = apidoc_to_markdown(api_data, project)

    groups = set()
    endpoints = 0
    for entry in api_data:
        if isinstance(entry, dict):
            groups.add(entry.get("group", "default"))
            endpoints += 1

    metadata: dict = {
        "api_title": (project or {}).get("title", (project or {}).get("name", "")),
        "api_version": (project or {}).get("version", ""),
        "detection_method": "apidoc",
        "endpoints": endpoints,
        "groups": len(groups),
    }

    logger.info("apidoc conversion completed", extra={
        "endpoints": endpoints,
        "groups": len(groups),
        "md_length": len(md_text),
    })

    return md_text, metadata
