"""PDF -> Markdown converter with optional OCR (Gemini Vision).

Two-pass pipeline (legacy) or async pipeline:
  Legacy: pymupdf4llm text extraction + synchronous OCR in one call
  Async:  convert_pdf_text_only (fast text) -> extract_pdf_images (S3) -> async OCR tasks

Language detection uses Gemini (same API key as embeddings) between passes.
"""

import logging
import os
import re
import shutil
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Callable

import pymupdf
import pymupdf4llm

from app.ingestion.converters.ocr import (
    OCR_IMAGE_MIN_AREA,
    detect_language_via_gemini,
    enrich_markdown_with_ocr_files,
    ocr_enabled,
)

from app.utils.retry import retry_call

logger = logging.getLogger(__name__)

PARALLEL_THRESHOLD = 10
MAX_PDF_WORKERS = 1
MAX_RETRIES = 2
PAGES_PER_CHUNK_SMALL = 2
PAGES_PER_CHUNK_LARGE = 10

IMAGE_PLACEHOLDER_PREFIX = "lexiro:image"
_PLACEHOLDER_RE = re.compile(
    r"!\[([^\]]*)\]\(lexiro:image:(\d+):(\d+)\)"
)

_XREF_WIDTH_RE = re.compile(r"/Width\s+(\d+)")
_XREF_HEIGHT_RE = re.compile(r"/Height\s+(\d+)")


@dataclass
class PdfImageInfo:
    """Metadata for a single OCR-worthy image extracted from a PDF."""
    seq: int
    page: int
    xref: int
    width: int
    height: int
    s3_key: str = ""


def _image_area_from_xref(doc: pymupdf.Document, xref: int) -> int:
    """Get image pixel area from xref metadata without decompressing the image."""
    try:
        obj_str = doc.xref_object(xref)
        w_match = _XREF_WIDTH_RE.search(obj_str)
        h_match = _XREF_HEIGHT_RE.search(obj_str)
        if w_match and h_match:
            return int(w_match.group(1)) * int(h_match.group(1))
    except Exception:
        pass
    return 0


def _image_dims_from_xref(doc: pymupdf.Document, xref: int) -> tuple[int, int]:
    """Get (width, height) from xref metadata."""
    try:
        obj_str = doc.xref_object(xref)
        w_match = _XREF_WIDTH_RE.search(obj_str)
        h_match = _XREF_HEIGHT_RE.search(obj_str)
        if w_match and h_match:
            return int(w_match.group(1)), int(h_match.group(1))
    except Exception:
        pass
    return 0, 0


def _find_ocr_pages(
    pdf_path: str,
    progress_callback: Callable[[float], None] | None = None,
) -> list[int]:
    doc = pymupdf.open(pdf_path)
    try:
        ocr_pages: list[int] = []
        total = doc.page_count
        for i in range(total):
            page = doc[i]
            for img_info in page.get_images():
                xref = img_info[0]
                if _image_area_from_xref(doc, xref) >= OCR_IMAGE_MIN_AREA:
                    ocr_pages.append(i)
                    break
            if progress_callback is not None and total > 0:
                progress_callback((i + 1) / total)
        return ocr_pages
    finally:
        doc.close()


def collect_ocr_images(pdf_path: str) -> list[PdfImageInfo]:
    """Scan PDF and return metadata for OCR-worthy images (above area threshold).

    Does NOT extract pixel data — only collects xref/page/dimensions.
    Deduplicates by xref so the same image embedded on multiple pages is listed once.

    seq is assigned as a global counter over ALL unique images (including small ones),
    so it matches the positional index of image refs in the markdown generated by
    pymupdf4llm. Only images above OCR_IMAGE_MIN_AREA are returned, but their seq
    values preserve the global ordering for correct placeholder-to-OCR mapping.
    """
    doc = pymupdf.open(pdf_path)
    try:
        seen_xrefs: set[int] = set()
        images: list[PdfImageInfo] = []
        seq = 0
        for page_idx in range(doc.page_count):
            page = doc[page_idx]
            for img_info in page.get_images():
                xref = img_info[0]
                if xref in seen_xrefs:
                    continue
                seen_xrefs.add(xref)
                w, h = _image_dims_from_xref(doc, xref)
                if w * h < OCR_IMAGE_MIN_AREA:
                    seq += 1
                    continue
                images.append(PdfImageInfo(
                    seq=seq, page=page_idx, xref=xref, width=w, height=h,
                ))
                seq += 1
        return images
    finally:
        doc.close()


def extract_and_upload_image(
    pdf_path: str,
    img: PdfImageInfo,
    document_id: int,
) -> str:
    """Extract a single image from PDF by xref and upload to S3.

    Returns the S3 key. The image is stored as PNG.
    """
    from app.s3 import upload_file

    doc = pymupdf.open(pdf_path)
    try:
        xref = img.xref
        img_data = doc.extract_image(xref)
        if not img_data or not img_data.get("image"):
            raise ValueError(f"Cannot extract image xref={xref}")

        raw_bytes = img_data["image"]
        ext = img_data.get("ext", "png")
        mime = {
            "png": "image/png",
            "jpeg": "image/jpeg",
            "jpg": "image/jpeg",
            "webp": "image/webp",
            "bmp": "image/bmp",
        }.get(ext, "image/png")

        s3_key = f"documents/{document_id}/ocr_images/{img.seq}.{ext}"
        upload_file(s3_key, raw_bytes, content_type=mime)
        return s3_key
    finally:
        doc.close()


def _convert_page_range_with_retry(
    file_path: str,
    page_range: list[int],
    image_path: str | None = None,
) -> str:
    """Convert pages with retry logic. Top-level for pickle serialisation."""
    def _convert():
        kwargs: dict = {"pages": page_range}
        if image_path:
            kwargs["write_images"] = True
            kwargs["image_path"] = image_path
        return pymupdf4llm.to_markdown(file_path, **kwargs)

    return retry_call(
        _convert,
        max_retries=MAX_RETRIES,
        base_delay=1.0,
        is_retryable=lambda _e: True,
        label=f"pdf_pages_{page_range[0]}-{page_range[-1]}",
    )


def _convert_page_range_text_only(file_path: str, page_range: list[int]) -> str:
    """Convert pages to markdown WITHOUT write_images (text-only, fast)."""
    def _convert():
        return pymupdf4llm.to_markdown(file_path, pages=page_range)

    return retry_call(
        _convert,
        max_retries=MAX_RETRIES,
        base_delay=1.0,
        is_retryable=lambda _e: True,
        label=f"pdf_text_{page_range[0]}-{page_range[-1]}",
    )


def _split_page_ranges(page_count: int, pages_per_chunk: int = PAGES_PER_CHUNK_SMALL) -> list[list[int]]:
    """Split pages into fixed-size chunks for granular progress reporting."""
    ranges: list[list[int]] = []
    for start in range(0, page_count, pages_per_chunk):
        end = min(start + pages_per_chunk, page_count)
        ranges.append(list(range(start, end)))
    return ranges


def _replace_image_refs_with_placeholders(
    md_text: str,
    document_id: int,
    ocr_images: list[PdfImageInfo],
) -> str:
    """Replace pymupdf4llm image markdown refs with stable placeholders.

    pymupdf4llm generates refs like ![alt](path/image.png).
    Each image ref gets a positional seq (0, 1, 2, ...) matching the global seq
    from collect_ocr_images. OCR-worthy refs become lexiro:image:DOC_ID:SEQ
    placeholders; small/non-OCR refs are removed (blank string).
    """
    from app.ingestion.converters.ocr import IMG_REF_RE

    matches = list(IMG_REF_RE.finditer(md_text))
    if not matches:
        return md_text

    ocr_seq_set = {img.seq for img in ocr_images}

    parts: list[str] = []
    last_end = 0
    for seq, match in enumerate(matches):
        parts.append(md_text[last_end:match.start()])
        if seq in ocr_seq_set:
            alt = match.group(1) or ""
            parts.append(f"![{alt}]({IMAGE_PLACEHOLDER_PREFIX}:{document_id}:{seq})")
        parts.append("")
        last_end = match.end()
    parts.append(md_text[last_end:])
    return "".join(parts)


def convert_pdf_text_only(
    file_path: str,
    document_id: int,
    progress_callback: Callable[[float, str], None] | None = None,
) -> tuple[str, dict, list[PdfImageInfo]]:
    """Fast text-only PDF conversion: extract text layer, skip OCR.

    Images above the OCR threshold are collected as PdfImageInfo for later
    async OCR processing. Image markdown refs in the text are replaced
    with stable placeholders: ![alt](lexiro:image:DOC_ID:SEQ).

    Returns:
        (markdown_text_with_placeholders, metadata, ocr_image_list)
    """
    t0 = time.perf_counter()
    file_size = os.path.getsize(file_path)
    doc = pymupdf.open(file_path)
    page_count = doc.page_count
    doc.close()

    if progress_callback is not None:
        progress_callback(0.0, "analyzing")

    ocr_images = collect_ocr_images(file_path) if ocr_enabled() else []
    has_images = len(ocr_images) > 0

    if progress_callback is not None:
        progress_callback(0.02, "analyzing")

    _convert_cb: Callable[[float], None] | None = None
    if progress_callback is not None:
        _convert_cb = lambda frac: progress_callback(0.02 + frac * 0.98, "converting")

    logger.info(
        "PDF text-only conversion started",
        extra={
            "file": os.path.basename(file_path), "pages": page_count,
            "file_size_bytes": file_size,
            "parallel": page_count > PARALLEL_THRESHOLD,
            "ocr_images_found": len(ocr_images),
        },
    )

    chunk_size = PAGES_PER_CHUNK_LARGE if page_count > PARALLEL_THRESHOLD else PAGES_PER_CHUNK_SMALL
    page_ranges = _split_page_ranges(page_count, pages_per_chunk=chunk_size)
    total_ranges = len(page_ranges)

    if page_count > PARALLEL_THRESHOLD:
        num_workers = min(MAX_PDF_WORKERS, page_count)
        results: dict[int, str] = {}
        completed_count = 0

        logger.info(
            "Parallel PDF text-only conversion",
            extra={
                "workers": num_workers,
                "total_chunks": total_ranges,
                "pages_per_chunk": chunk_size,
            },
        )

        with ThreadPoolExecutor(max_workers=num_workers) as executor:
            future_to_idx = {
                executor.submit(
                    _convert_page_range_text_only, file_path, pr,
                ): idx
                for idx, pr in enumerate(page_ranges)
            }
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                results[idx] = future.result()
                completed_count += 1
                if _convert_cb is not None:
                    _convert_cb(completed_count / total_ranges)

        md_text = "\n\n".join(results[i] for i in range(total_ranges))
    else:
        page_results: dict[int, str] = {}
        for idx, pr in enumerate(page_ranges):
            page_results[idx] = _convert_page_range_text_only(file_path, pr)
            if _convert_cb is not None:
                _convert_cb((idx + 1) / total_ranges)

        md_text = "\n\n".join(page_results[i] for i in range(total_ranges))

    if has_images:
        md_text = _replace_image_refs_with_placeholders(md_text, document_id, ocr_images)

    convert_ms = round((time.perf_counter() - t0) * 1000, 1)

    metadata: dict = {
        "pages": page_count,
        "file_size_bytes": file_size,
        "convert_ms": convert_ms,
        "ocr_applied": False,
        "ocr_deferred": has_images,
        "ocr_images_found": len(ocr_images),
        "parallel_workers": min(MAX_PDF_WORKERS, page_count) if page_count > PARALLEL_THRESHOLD else 1,
        "total_ms": convert_ms,
    }

    logger.info(
        "PDF text-only conversion completed",
        extra={
            "file": os.path.basename(file_path), "pages": page_count,
            "convert_ms": convert_ms,
            "ocr_deferred": has_images,
            "ocr_images_found": len(ocr_images),
            "md_length": len(md_text),
        },
    )

    return md_text, metadata, ocr_images


def replace_placeholders_with_ocr(
    md_text: str,
    ocr_results: dict[str, str],
) -> str:
    """Replace lexiro:image placeholders in markdown with OCR text.

    Args:
        md_text: Markdown text containing ![...](lexiro:image:DOC:SEQ) placeholders.
        ocr_results: Mapping of "DOC_ID:SEQ" -> recognized text.
            Missing or empty entries leave the placeholder removed (blank).

    Returns:
        Updated markdown text.
    """
    def _replacer(match: re.Match) -> str:
        doc_id = match.group(2)
        seq = match.group(3)
        key = f"{doc_id}:{seq}"
        text = ocr_results.get(key, "").strip()
        return text

    return _PLACEHOLDER_RE.sub(_replacer, md_text)


# ---------------------------------------------------------------------------
# Legacy synchronous convert_pdf (kept for backward compatibility)
# ---------------------------------------------------------------------------

def convert_pdf(
    file_path: str,
    progress_callback: Callable[[float, str], None] | None = None,
) -> tuple[str, dict]:
    """Convert PDF to Markdown text with parallel page processing and OCR.

    Two-pass pipeline:
      Pass 1: pymupdf4llm text extraction (parallel for large PDFs)
      Pass 2: OCR all images with auto-detected language via Gemini Vision

    Language is detected automatically via Gemini after Pass 1.
    Falls back to English if detection fails.

    Progress is reported via callback: progress_callback(fraction, stage)
    where fraction is in [0..1] and stage is "converting" or "ocr".
    If images found: converting = 0->0.625, OCR = 0.625->1.0.
    If no images: converting = full 0->1.0 range.

    Args:
        file_path: Path to the PDF file.
        progress_callback: fn(fraction, stage) called as conversion progresses.

    Returns:
        (markdown_text, metadata) where metadata includes conversion stats.
    """
    t0 = time.perf_counter()
    file_size = os.path.getsize(file_path)
    doc = pymupdf.open(file_path)
    page_count = doc.page_count
    doc.close()

    if progress_callback is not None:
        progress_callback(0.0, "analyzing")

    def _analyze_cb(frac: float) -> None:
        if progress_callback is not None:
            progress_callback(frac * 0.05, "analyzing")

    ocr_pages = _find_ocr_pages(file_path, progress_callback=_analyze_cb)
    has_ocr_images = len(ocr_pages) > 0
    will_ocr = has_ocr_images and ocr_enabled()

    if progress_callback is not None:
        if will_ocr:
            _convert_cb = lambda frac: progress_callback(0.05 + frac * 0.575, "converting")
            _ocr_cb = lambda frac: progress_callback(0.625 + frac * 0.375, "ocr")
        else:
            _convert_cb = lambda frac: progress_callback(0.05 + frac * 0.95, "converting")
            _ocr_cb = None
    else:
        _convert_cb = None
        _ocr_cb = None

    image_temp_dir: str | None = None
    if will_ocr:
        image_temp_dir = tempfile.mkdtemp(prefix="pdf_ocr_images_")
        logger.debug("Created temp dir for OCR images", extra={"path": image_temp_dir})

    logger.info(
        "PDF conversion started",
        extra={
            "file": os.path.basename(file_path), "pages": page_count,
            "file_size_bytes": file_size,
            "parallel": page_count > PARALLEL_THRESHOLD,
            "will_ocr": will_ocr,
        },
    )

    chunk_size = PAGES_PER_CHUNK_LARGE if page_count > PARALLEL_THRESHOLD else PAGES_PER_CHUNK_SMALL
    page_ranges = _split_page_ranges(page_count, pages_per_chunk=chunk_size)
    total_ranges = len(page_ranges)

    ocr_page_set = set(ocr_pages) if will_ocr else set()

    def _image_path_for_range(pr: list[int]) -> str | None:
        """Return image_temp_dir only when the page range has OCR-worthy pages."""
        if not image_temp_dir:
            return None
        if ocr_page_set.intersection(pr):
            return image_temp_dir
        return None

    try:
        if page_count > PARALLEL_THRESHOLD:
            num_workers = min(MAX_PDF_WORKERS, page_count)
            results: dict[int, str] = {}
            completed_count = 0

            logger.info(
                "Parallel PDF conversion",
                extra={
                    "workers": num_workers,
                    "total_chunks": total_ranges,
                    "pages_per_chunk": chunk_size,
                    "ocr_pages_count": len(ocr_page_set),
                },
            )

            with ThreadPoolExecutor(max_workers=num_workers) as executor:
                future_to_idx = {
                    executor.submit(
                        _convert_page_range_with_retry, file_path, pr,
                        _image_path_for_range(pr),
                    ): idx
                    for idx, pr in enumerate(page_ranges)
                }
                for future in as_completed(future_to_idx):
                    idx = future_to_idx[future]
                    results[idx] = future.result()
                    completed_count += 1
                    if _convert_cb is not None:
                        _convert_cb(completed_count / total_ranges)

            md_text = "\n\n".join(results[i] for i in range(total_ranges))
        else:
            page_results: dict[int, str] = {}
            for idx, pr in enumerate(page_ranges):
                img_path = _image_path_for_range(pr)

                def _convert_range(_pr=pr, _img=img_path):
                    kwargs: dict = {"pages": _pr}
                    if _img:
                        kwargs["write_images"] = True
                        kwargs["image_path"] = _img
                    return pymupdf4llm.to_markdown(file_path, **kwargs)

                page_results[idx] = retry_call(
                    _convert_range,
                    max_retries=MAX_RETRIES,
                    base_delay=1.0,
                    is_retryable=lambda _e: True,
                    label=f"pdf_page_{pr[0]}",
                )
                if _convert_cb is not None:
                    _convert_cb((idx + 1) / total_ranges)

            md_text = "\n\n".join(page_results[i] for i in range(total_ranges))

        convert_ms = round((time.perf_counter() - t0) * 1000, 1)

        metadata: dict = {
            "pages": page_count,
            "file_size_bytes": file_size,
            "convert_ms": convert_ms,
            "ocr_applied": False,
            "parallel_workers": min(MAX_PDF_WORKERS, page_count) if page_count > PARALLEL_THRESHOLD else 1,
        }

        if will_ocr:
            try:
                detected_langs, lang_usage = detect_language_via_gemini(md_text)
                metadata["detected_languages"] = detected_langs
                metadata["detected_languages_str"] = ",".join(detected_langs)

                t_ocr = time.perf_counter()
                md_text, ocr_stats = enrich_markdown_with_ocr_files(
                    md_text, languages=detected_langs,
                    progress_callback=_ocr_cb,
                )
                ocr_stats["ocr_prompt_tokens"] = ocr_stats.get("ocr_prompt_tokens", 0) + lang_usage.get("prompt_tokens", 0)
                ocr_stats["ocr_completion_tokens"] = ocr_stats.get("ocr_completion_tokens", 0) + lang_usage.get("completion_tokens", 0)
                ocr_ms = round((time.perf_counter() - t_ocr) * 1000, 1)
                metadata["ocr_applied"] = True
                metadata["ocr_ms"] = ocr_ms
                metadata["ocr_stats"] = ocr_stats
                logger.info(
                    "OCR completed",
                    extra={
                        "ocr_ms": ocr_ms,
                        "detected_languages": detected_langs,
                        "ocr_images_total": ocr_stats["ocr_images_total"],
                        "ocr_images_success": ocr_stats["ocr_images_success"],
                        "ocr_images_failed": ocr_stats["ocr_images_failed"],
                    },
                )
            except Exception as ocr_exc:
                ocr_error_msg = f"{type(ocr_exc).__name__}: {ocr_exc}"
                logger.error(
                    "OCR phase failed entirely — continuing without OCR",
                    extra={
                        "file": os.path.basename(file_path),
                        "error": ocr_error_msg[:500],
                    },
                    exc_info=True,
                )
                metadata["ocr_applied"] = False
                metadata["ocr_error"] = ocr_error_msg[:500]
                metadata["ocr_stats"] = {
                    "ocr_images_total": 0,
                    "ocr_images_success": 0,
                    "ocr_images_empty": 0,
                    "ocr_images_failed": 0,
                }

        total_ms = round((time.perf_counter() - t0) * 1000, 1)
        metadata["total_ms"] = total_ms

        logger.info(
            "PDF conversion completed",
            extra={
                "file": os.path.basename(file_path), "pages": page_count,
                "total_ms": total_ms, "ocr_applied": metadata["ocr_applied"],
                "md_length": len(md_text),
            },
        )

        return md_text, metadata

    finally:
        if image_temp_dir and os.path.isdir(image_temp_dir):
            try:
                shutil.rmtree(image_temp_dir)
                logger.debug("Cleaned up OCR temp dir", extra={"path": image_temp_dir})
            except Exception as cleanup_exc:
                logger.warning(
                    "Failed to clean up OCR temp dir",
                    extra={"path": image_temp_dir, "error": str(cleanup_exc)[:200]},
                )
