"""URL -> Markdown converter.

Auto-detects content type:
- Postman Documenter published page -> fetches collection JSON via API
- Direct Swagger/OpenAPI spec (JSON/YAML) -> structured Markdown
- Swagger UI / ReDoc page -> extracts spec URL, then parses
- apiDoc.js page -> extracts api_data.js / api_project.js, parses
- Generic web page -> headless browser via httpx + optional Crawl4AI

Crawl4AI is optional: if not installed, falls back to httpx for simple pages.
"""

import asyncio
import base64
import json
import logging
import re
import ssl
import time
import urllib.request
from urllib.parse import urlparse, urljoin

import yaml

from app.ingestion.converters.apidoc import parse_apidoc_js
from app.ingestion.converters.postman import _postman_to_markdown
from app.ingestion.converters.swagger import _openapi_to_markdown, _parse_openapi_text

logger = logging.getLogger(__name__)

_FETCH_TIMEOUT = 30
_MAX_RESPONSE_BYTES = 50 * 1024 * 1024

_SWAGGER_NAMES = {"swagger", "openapi", "paths", "info"}

_SWAGGER_UI_PATTERNS = re.compile(
    r"swagger-ui|SwaggerUIBundle|redoc\.standalone|spec-url|swagger-config",
    re.IGNORECASE,
)

_APIDOC_PATTERNS = re.compile(
    r"apidoc\.js|api_data\.js|api_project\.js|generator[\"']:\s*[\"']apidoc",
    re.IGNORECASE,
)

_SPEC_URL_EXTRACTORS = [
    re.compile(r"""url\s*[:=]\s*['"]([^'"]+\.(?:json|yaml|yml))['"]"""),
    re.compile(r"""spec-url\s*=\s*['"]([^'"]+)['"]"""),
    re.compile(r"""configUrl\s*[:=]\s*['"]([^'"]+)['"]"""),
]

_COMMON_SPEC_PATHS = [
    "/swagger.json", "/openapi.json", "/api-docs",
    "/v2/api-docs", "/v3/api-docs",
    "/swagger/v1/swagger.json", "/swagger.yaml",
]

_POSTMAN_DOCUMENTER_RE = re.compile(
    r"^https?://documenter\.getpostman\.com/view/(\d+)/(\w+)"
)


def _make_ssl_context() -> ssl.SSLContext:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def _fetch_url(
    url: str,
    accept: str = "*/*",
    auth: tuple[str, str] | None = None,
    bearer_token: str | None = None,
) -> tuple[bytes, str, str]:
    """Fetch URL content. Returns (body_bytes, content_type, final_url).

    Args:
        auth: Optional (username, password) for HTTP Basic Authentication.
        bearer_token: Optional Bearer token for Authorization header.
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Lexiro/1.0",
        "Accept": accept,
    }
    if bearer_token:
        headers["Authorization"] = f"Bearer {bearer_token}"
    elif auth:
        credentials = base64.b64encode(f"{auth[0]}:{auth[1]}".encode()).decode()
        headers["Authorization"] = f"Basic {credentials}"

    req = urllib.request.Request(url, headers=headers)
    ctx = _make_ssl_context()
    with urllib.request.urlopen(req, timeout=_FETCH_TIMEOUT, context=ctx) as resp:
        ct = resp.headers.get("Content-Type", "")
        final_url = resp.url
        body = resp.read(_MAX_RESPONSE_BYTES)
    return body, ct, final_url


def _detect_postman_documenter(url: str) -> tuple[str, str] | None:
    """Return (user_id, published_id) if *url* is a Postman Documenter link."""
    m = _POSTMAN_DOCUMENTER_RE.match(url)
    if m:
        return m.group(1), m.group(2)
    return None


def _fetch_postman_collection(user_id: str, published_id: str) -> dict:
    """Fetch full Postman Collection JSON from the documenter API."""
    api_url = (
        f"https://documenter.getpostman.com/api/collections/"
        f"{user_id}/{published_id}"
    )
    body, _, _ = _fetch_url(api_url, accept="application/json")
    return json.loads(body.decode("utf-8"))


def _try_parse_as_openapi(raw: bytes, content_type: str) -> dict | None:
    text = raw.decode("utf-8", errors="replace")
    return _parse_openapi_text(text, content_type)


def _detect_swagger_spec_url(html: str, page_url: str) -> str | None:
    if not _SWAGGER_UI_PATTERNS.search(html):
        return None
    for pattern in _SPEC_URL_EXTRACTORS:
        m = pattern.search(html)
        if m:
            spec_url = m.group(1)
            if spec_url.startswith("/"):
                parsed = urlparse(page_url)
                spec_url = f"{parsed.scheme}://{parsed.netloc}{spec_url}"
            elif not spec_url.startswith("http"):
                base = page_url.rsplit("/", 1)[0]
                spec_url = f"{base}/{spec_url}"
            return spec_url

    parsed = urlparse(page_url)
    base = f"{parsed.scheme}://{parsed.netloc}"
    for path in _COMMON_SPEC_PATHS:
        probe_url = base + path
        try:
            body, ct, _ = _fetch_url(probe_url, accept="application/json, application/yaml")
            if _try_parse_as_openapi(body, ct) is not None:
                return probe_url
        except Exception:
            continue
    return None


def _detect_apidoc_page(html: str) -> bool:
    """Check if HTML page is generated by apiDoc.js."""
    return bool(_APIDOC_PATTERNS.search(html))


def _fetch_apidoc_data(
    page_url: str,
    html: str,
    auth: tuple[str, str] | None = None,
    bearer_token: str | None = None,
) -> tuple[str, str] | None:
    """Try to fetch api_data.js and api_project.js relative to the page URL.

    Returns (api_data_js_content, api_project_js_content) or None.
    """
    parsed = urlparse(page_url)
    base = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    if not base.endswith("/"):
        base = base.rsplit("/", 1)[0] + "/"

    candidate_bases = [base]
    for script_re in [
        re.compile(r'src=["\']([^"\']*api_data\.js[^"\']*)["\']', re.IGNORECASE),
    ]:
        m = script_re.search(html)
        if m:
            script_path = m.group(1).split("?")[0]
            data_url = urljoin(page_url, script_path)
            data_base = data_url.rsplit("/", 1)[0] + "/"
            if data_base not in candidate_bases:
                candidate_bases.insert(0, data_base)

    api_data_js = ""
    api_project_js = ""

    for cb in candidate_bases:
        if api_data_js:
            break
        data_url = urljoin(cb, "api_data.js")
        try:
            body, _, _ = _fetch_url(data_url, accept="*/*", auth=auth, bearer_token=bearer_token)
            text = body.decode("utf-8", errors="replace")
            if "api" in text.lower() and len(text) > 50:
                api_data_js = text
                proj_url = urljoin(cb, "api_project.js")
                try:
                    pbody, _, _ = _fetch_url(proj_url, accept="*/*", auth=auth, bearer_token=bearer_token)
                    api_project_js = pbody.decode("utf-8", errors="replace")
                except Exception:
                    pass
                break
        except Exception:
            continue

    if not api_data_js:
        return None
    return api_data_js, api_project_js


def _crawl4ai_available() -> bool:
    try:
        import crawl4ai  # noqa: F401
        return True
    except ImportError:
        return False


async def _crawl_url(url: str, wait_for: str | None = None, delay: float = 0) -> tuple[str, str]:
    """Crawl a single URL with headless browser. Returns (markdown, page_title)."""
    from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig, CacheMode
    from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
    from crawl4ai.content_filter_strategy import PruningContentFilter

    md_gen = DefaultMarkdownGenerator(
        content_filter=PruningContentFilter(threshold=0.4, threshold_type="fixed")
    )

    run_cfg_kwargs: dict = {
        "cache_mode": CacheMode.BYPASS,
        "markdown_generator": md_gen,
    }
    if wait_for:
        run_cfg_kwargs["wait_for"] = wait_for
    if delay:
        run_cfg_kwargs["delay_before_return_html"] = delay

    browser_cfg = BrowserConfig(headless=True)
    run_cfg = CrawlerRunConfig(**run_cfg_kwargs)

    async with AsyncWebCrawler(config=browser_cfg) as crawler:
        result = await crawler.arun(url=url, config=run_cfg)
        if not result.success:
            raise RuntimeError(result.error_message or "Crawl failed")
        md = result.markdown
        if hasattr(md, "fit_markdown") and md.fit_markdown:
            md_text = md.fit_markdown
        elif hasattr(md, "raw_markdown"):
            md_text = md.raw_markdown
        else:
            md_text = str(md)
        title = ""
        if result.metadata and isinstance(result.metadata, dict):
            title = result.metadata.get("title", "")
        return md_text, title


async def convert_url(
    url: str,
    auth: tuple[str, str] | None = None,
    bearer_token: str | None = None,
) -> tuple[str, dict]:
    """Convert a URL to Markdown text.

    Auto-detects: direct OpenAPI spec, Swagger UI page, apiDoc.js page,
    or generic web page.

    Args:
        url: Web page URL.
        auth: Optional (username, password) for HTTP Basic Auth.
        bearer_token: Optional Bearer token for Authorization header.

    Returns (markdown_text, metadata).
    """
    t0 = time.perf_counter()
    url = url.strip()

    logger.info("URL conversion started", extra={"url": url, "has_auth": auth is not None or bearer_token is not None})

    # --- Postman Documenter shortcut (SPA that cannot be fetched normally) ---
    postman_match = _detect_postman_documenter(url)
    if postman_match:
        user_id, published_id = postman_match
        logger.info("Detected Postman Documenter URL", extra={
            "url": url, "user_id": user_id, "published_id": published_id,
        })
        collection = await asyncio.to_thread(
            _fetch_postman_collection, user_id, published_id,
        )
        md_text = _postman_to_markdown(collection)
        total_ms = round((time.perf_counter() - t0) * 1000, 1)

        if not md_text or not md_text.strip():
            raise ValueError(f"Conversion of {url} produced empty content")

        info = collection.get("info", {})

        def _count(items: list, key: str) -> int:
            n = 0
            for item in items:
                if isinstance(item, dict):
                    sub = item.get("item")
                    if isinstance(sub, list):
                        n += (1 if key == "folders" else 0) + _count(sub, key)
                    elif key == "requests" and "request" in item:
                        n += 1
            return n

        items = collection.get("item", [])
        metadata: dict = {
            "url": url,
            "detection_method": "postman_documenter",
            "page_title": info.get("name", ""),
            "total_ms": total_ms,
            "fetch_ms": total_ms,
            "md_length": len(md_text),
            "collection_name": info.get("name", ""),
            "postman_id": info.get("_postman_id", ""),
            "requests": _count(items, "requests"),
            "folders": _count(items, "folders"),
        }

        logger.info("URL conversion completed (Postman Documenter)", extra={
            "url": url, "detection": "postman_documenter",
            "total_ms": total_ms, "md_length": len(md_text),
            "requests": metadata["requests"], "folders": metadata["folders"],
        })
        return md_text, metadata

    # --- Standard URL processing ---
    detection_method = "unknown"
    spec: dict | None = None
    md_text: str = ""
    page_title: str = ""

    raw_body, content_type, final_url = await asyncio.to_thread(
        _fetch_url, url, "application/json, application/yaml, text/html, */*",
        auth, bearer_token,
    )
    fetch_ms = round((time.perf_counter() - t0) * 1000, 1)
    logger.debug("URL fetched", extra={"url": url, "fetch_ms": fetch_ms, "content_type": content_type})

    spec = _try_parse_as_openapi(raw_body, content_type)
    if spec:
        detection_method = "direct_openapi_spec"
        logger.info("Detected direct OpenAPI spec", extra={"url": url})
    else:
        body_text = raw_body.decode("utf-8", errors="replace")
        is_html = (
            "html" in content_type.lower()
            or body_text.lstrip().startswith("<!")
            or "<html" in body_text[:500].lower()
        )
        if is_html:
            # --- apiDoc.js detection (before Swagger UI) ---
            if _detect_apidoc_page(body_text):
                logger.info("apiDoc.js page detected, fetching api_data.js", extra={"url": url})
                apidoc_result = await asyncio.to_thread(
                    _fetch_apidoc_data, final_url, body_text, auth, bearer_token,
                )
                if apidoc_result:
                    api_data_js, api_project_js = apidoc_result
                    try:
                        md_text, apidoc_meta = parse_apidoc_js(api_data_js, api_project_js)
                        detection_method = "apidoc"
                        page_title = apidoc_meta.get("api_title", "")
                        total_ms = round((time.perf_counter() - t0) * 1000, 1)

                        if md_text and md_text.strip():
                            metadata: dict = {
                                "url": url,
                                "detection_method": "apidoc",
                                "page_title": page_title,
                                "total_ms": total_ms,
                                "fetch_ms": fetch_ms,
                                "md_length": len(md_text),
                                **{k: v for k, v in apidoc_meta.items() if k != "detection_method"},
                            }
                            logger.info("URL conversion completed (apiDoc)", extra={
                                "url": url, "detection": "apidoc",
                                "total_ms": total_ms, "md_length": len(md_text),
                                "endpoints": apidoc_meta.get("endpoints", 0),
                            })
                            return md_text, metadata
                    except Exception as exc:
                        logger.warning("apiDoc parsing failed, will try other methods", extra={
                            "url": url, "error": str(exc)[:300],
                        })

            # --- Swagger UI / ReDoc detection ---
            spec_url = await asyncio.to_thread(_detect_swagger_spec_url, body_text, final_url)
            if spec_url:
                logger.info("Swagger UI detected, fetching spec", extra={"spec_url": spec_url})
                try:
                    spec_body, spec_ct, _ = await asyncio.to_thread(
                        _fetch_url, spec_url, "application/json, application/yaml",
                        auth, bearer_token,
                    )
                    spec = _try_parse_as_openapi(spec_body, spec_ct)
                    if spec:
                        detection_method = "swagger_ui_extracted"
                except Exception as exc:
                    logger.warning("Failed to fetch extracted spec URL", extra={
                        "spec_url": spec_url, "error_type": type(exc).__name__,
                    })

    if spec:
        md_text = _openapi_to_markdown(spec)
        info = spec.get("info", {})
        page_title = info.get("title", "")
    elif not md_text:
        detection_method = "crawl4ai_fallback"
        if _crawl4ai_available():
            logger.info("Falling back to Crawl4AI", extra={"url": url})
            md_text, page_title = await _crawl_url(url, None, 2.0)
        else:
            body_text = raw_body.decode("utf-8", errors="replace")
            md_text = body_text
            detection_method = "raw_html_fallback"
            logger.warning("Crawl4AI not available, using raw HTML", extra={"url": url})

    total_ms = round((time.perf_counter() - t0) * 1000, 1)

    if not md_text or not md_text.strip():
        logger.warning("URL conversion produced empty content", extra={"url": url, "detection": detection_method})
        raise ValueError(f"Conversion of {url} produced empty content")

    metadata: dict = {
        "url": url,
        "detection_method": detection_method,
        "page_title": page_title,
        "total_ms": total_ms,
        "fetch_ms": fetch_ms,
        "md_length": len(md_text),
    }

    if spec:
        info = spec.get("info", {})
        metadata["api_title"] = info.get("title", "")
        metadata["api_version"] = info.get("version", "")
        metadata["endpoints"] = sum(
            len([m for m in ("get", "post", "put", "patch", "delete", "options", "head") if m in ops])
            for ops in spec.get("paths", {}).values()
            if isinstance(ops, dict)
        )
        metadata["models"] = len(
            spec.get("definitions") or spec.get("components", {}).get("schemas", {}) or {}
        )

    logger.info(
        "URL conversion completed",
        extra={
            "url": url, "detection": detection_method,
            "total_ms": total_ms, "md_length": len(md_text),
        },
    )

    return md_text, metadata
